---
title: "Using Label Studio"
format: html
---

Label Studio is an annotating software that runs on your computer that will
allow you to annotate images.

## Installation

### Install conda (or use another environment manager)

- [macOS](https://docs.conda.io/projects/conda/en/stable/user-guide/install/macos.html)
- [Windows](https://docs.conda.io/projects/conda/en/stable/user-guide/install/windows.html)

### Create an environment with a Python version that works

In your terminal, run the following:

```bash
conda create -n label_studio python=3.11
```

### Activate the environment

Run:

```bash
conda activate label_studio
```

### Make sure pip is installed

Run:

```bash
conda install pip
```

### Install Label Studio

Run:

```bash
pip install label-studio
```

### Start the app

Run:

```bash
label-studio
```

> **Note:** Press <kbd>Control</kbd> + <kbd>C</kbd> in the terminal to quit the
> application.

## Getting Started

Set up an account when you first run the program.

> **Important:** Don't forget this login or you won't be able to access your
> projects.

## Beginning a New Project

1. **Create New Project**
2. **Add a project name**
   - Name it after the image folder name.
3. **Data Import**
   - Drag and drop all the images into it.
4. **Labeling setup**
   - Select **"Object Detection with Bounding Boxes"**.
   - Delete the Airport and Car example.
   - Under **"Add label names"**, add the labels to be used, each on their own
     line.

   > **Important:** It is very important that the same order and number for
   > labels is used every time. Each annotation will be defined by a number.
   > Not keeping numbers and labels lined up across annotations will ruin the
   > object detection model training.

   This is the running label list:

   | Number | Label  |
   |:------:|:-------|
   | 1      | Car    |
   | 2      | Window |

5. **Save Project.** This will take you to the annotation list.

## Annotating Images

### Standards

- Make sure the entire object is in the bounding box. There will be things that
  are not the object in each bounding box, but try to limit it.
- Annotate every instance of each object in the photo, even if it's related to
  another house — such as a car in the neighboring house's driveway, or a window
  on a neighboring house. When training the software, it doesn't matter if
  everything relates to the subject.
  - This also applies to objects that are only partly in a picture. The object
    detection model will still detect these.
- Again, labels must always have the same numbers associated with them, such as
  1 for car.
