import os
import json
import cv2
import numpy as np
import open3d as o3d

def load_opensfm_camera(reconstruction_file, image_filename):
    """
    Extracts the camera intrinsics and extrinsics for a specific image
    from OpenSfM's reconstruction.json and converts them to OpenCV format.
    """
    with open(reconstruction_file, 'r') as f:
        # OpenSfM usually stores the reconstruction as the first item in a list
        reconstruction = json.load(f)[0] 
        
    if image_filename not in reconstruction['shots']:
        raise ValueError(f"Error: Image '{image_filename}' not found in the reconstruction data.")
        
    shot = reconstruction['shots'][image_filename]
    camera_id = shot['camera']
    camera = reconstruction['cameras'][camera_id]
    
    # 1. Extrinsics: OpenSfM rotation and translation map World to Camera natively
    rvec = np.array(shot['rotation'], dtype=float)
    tvec = np.array(shot['translation'], dtype=float)
    
    # 2. Intrinsics: Map OpenSfM normalized focal length to OpenCV Matrix
    w = camera['width']
    h = camera['height']
    max_size = max(w, h)
    
    focal = camera.get('focal', 0.8) # OpenSfM normalizes focal length by max image dimension
    fx = focal * max_size
    fy = focal * max_size
    
    # OpenSfM principal point is relative to center and normalized
    c_x = camera.get('c_x', 0.0)
    c_y = camera.get('c_y', 0.0)
    cx = (w / 2.0) + (c_x * max_size)
    cy = (h / 2.0) + (c_y * max_size)
    
    camera_matrix = np.array([
        [fx, 0, cx],
        [0, fy, cy],
        [0, 0, 1]
    ], dtype=float)
    
    # 3. Distortion Coefficients: [k1, k2, p1, p2, k3]
    dist_coeffs = np.array([
        camera.get('k1', 0.0),
        camera.get('k2', 0.0),
        camera.get('p1', 0.0),
        camera.get('p2', 0.0),
        camera.get('k3', 0.0)
    ], dtype=float)
    
    return rvec, tvec, camera_matrix, dist_coeffs

def get_3d_bounding_box(ply_path):
    """Loads a PLY file and returns the 8 corners of its 3D bounding box."""
    pcd = o3d.io.read_point_cloud(ply_path)
    
    # Get Axis-Aligned Bounding Box
    aabb = pcd.get_axis_aligned_bounding_box()
    corners_3d = np.asarray(aabb.get_box_points())
    
    return corners_3d

def crop_house_from_image(image_path, ply_path, reconstruction_file, output_path, padding=50):
    """
    Projects the 3D bounding box onto the 2D image and crops the subject.
    """
    image_name = os.path.basename(image_path)
    print(f"Processing '{image_name}'...")
    
    # 1. Fetch parameters
    rvec, tvec, K, dist = load_opensfm_camera(reconstruction_file, image_name)
    
    # 2. Get 3D corners from the point cloud
    corners_3d = get_3d_bounding_box(ply_path)
    
    # 3. Project 3D coordinates onto the 2D image plane
    corners_2d, _ = cv2.projectPoints(corners_3d, rvec, tvec, K, dist)
    corners_2d = corners_2d.reshape(-1, 2)
    
    # 4. Calculate the 2D bounding box
    x_min = int(np.floor(np.min(corners_2d[:, 0])))
    x_max = int(np.ceil(np.max(corners_2d[:, 0])))
    y_min = int(np.floor(np.min(corners_2d[:, 1])))
    y_max = int(np.ceil(np.max(corners_2d[:, 1])))
    
    # 5. Load and crop the image using NumPy slicing
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(f"Could not load image at {image_path}")
        
    h, w = img.shape[:2]
    
    # Apply padding and clamp values to ensure we don't slice outside the array
    x_min = max(0, x_min - padding)
    y_min = max(0, y_min - padding)
    x_max = min(w, x_max + padding)
    y_max = min(h, y_max + padding)
    
    cropped_img = img[y_min:y_max, x_min:x_max]
    
    # 6. Save the output
    cv2.imwrite(output_path, cropped_img)
    print(f"Success! Cropped image saved to: {output_path}")
    print(f"Original Dimensions: {w}x{h} | Cropped Dimensions: {x_max-x_min}x{y_max-y_min}")

if __name__ == "__main__":
    # --- SETUP YOUR TEST PATHS HERE ---
    # Update these paths to point to a specific test case on your local machine
    
    # The full, uncropped original photo from the drone
    TEST_IMAGE = "data/900EBlock/images/DJI_001.JPG" 
    
    # The extracted point cloud for ONE house
    TEST_PLY = "data/900EBlock/analysis_900EBlock_v4_2/individual_houses/900EBlock_1.ply" 
    
    # The reconstruction metadata file generated by OpenSfM
    TEST_RECONSTRUCTION = "data/900EBlock/reconstruction.json" 
    
    # Where you want the test output to go
    OUTPUT_IMAGE = "cropped_test_house.jpg"
    
    try:
        crop_house_from_image(
            image_path=TEST_IMAGE, 
            ply_path=TEST_PLY, 
            reconstruction_file=TEST_RECONSTRUCTION, 
            output_path=OUTPUT_IMAGE,
            padding=60 # Adds a 60-pixel buffer around the house to ensure edges aren't lost
        )
    except Exception as e:
        print(f"Failed to process image: {e}")